### ISSUE TITLE
Nested route trick

### ISSUE THREAD

**Issue by nacpapa** [allestaire/ionic-7-react-nested-route#1]
Hello friend, I open an issue because I couldn't contact you in any other way. I was fighting for several days with the same problem as you and I applied your solution, but when the application grew I realized that the rerendering at 500ms generated performance problems and flickering on the screen (obvious when u think that the entire component is being rendered). ) in forums I found the following fix that was perfect for me: 
https://github.com/ionic-team/ionic-framework/issues/20597#issuecomment-648468733
I hope you find it useful

**Comment by allestaire** [comment]
Wow, I am amazed that you reached out 😄

**Comment by allestaire** [comment]
Thanks on this alot, you can put `IonPage` on router outlet, I didnt know this, this is so helpful
